### ISSUE TITLE
Removed rules in documentation

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [eslint/website#701] opened 2020-03-04 09:07 UTC
The following rule pages respond with 404 when access from the [rule list](https://eslint.org/docs/rules/). ESlint CLI doesn't recognized these either:
- default-case-last
- no-useless-backreference
- no-restricted-exports

**Comment by mdjermanovic** [comment] 2020-03-04 21:16
Sorry about that! These are actually new rules that will be available in `v7.0.0`:

* https://eslint.org/docs/7.0.0/rules/default-case-last
* https://eslint.org/docs/7.0.0/rules/no-useless-backreference
* https://eslint.org/docs/7.0.0/rules/no-restricted-exports

You can install `v7.0.0-alpha.2`  and try out the rules with: `npm i eslint@next --save-dev`

These rules shouldn't appear in the list for the actual version, and that's a bug we should fix.

I'm closing this as a duplicate of  #688

**Closed by mdjermanovic** 2020-03-04 21:16 UTC
